// Curated, real mind maps to show on the landing page.
//
// Every one of these was generated by the live YouTube flow
// (POST /yt/transform on the api worker), then hand-picked. The full source is
// committed next to this file rather than fetched from the API at render time,
// for three reasons: the landing page must not depend on the API being up to
// draw itself, `robots.txt` disallows /svg so a crawler would never see an
// API-served thumbnail, and a source in the repo is reviewable in a PR before
// it goes public.
//
// `shareId` is the 11-char content hash under which the api worker stored the
// same payload, so the card can link to the canonical /s/<id> page. It is NOT
// how the preview is drawn.
//
// Adding one: generate a map, save its source as `<slug>.mmd` here (ASCII only
// -- the model emits curly quotes and non-breaking hyphens, normalise them),
// then add an entry below. `pnpm --filter @mindmaply/editor test` checks that
// every source parses and that ids and slugs are well formed.

import jobsSource from './steve-jobs-stanford-2005.mmd?raw'
import roslingSource from './hans-rosling-best-stats.mmd?raw'
import mcravenSource from './mcraven-make-your-bed.mmd?raw'
import pauschSource from './randy-pausch-last-lecture.mmd?raw'
import { SHARE_BASE } from '../share'

export interface Example {
  /** URL-safe id. Reserved for the prerendered /examples/<slug>/ pages. */
  slug: string
  /** Human title. Shorter than the YouTube title, which is often unwieldy. */
  title: string
  /** One sentence. Doubles as the meta description on the per-example page. */
  blurb: string
  /** 11-char content-hash id stored by the api worker (see /shorten). */
  shareId: string
  /** Source video, credited on the card. */
  videoId: string
  /** The full generated map. */
  source: string
}

export const EXAMPLES: Example[] = [
  {
    slug: 'steve-jobs-stanford-2005',
    title: "Steve Jobs' 2005 Stanford Commencement Address",
    blurb:
      'The three-stories speech, mapped: connecting the dots, love and loss, and death, each with the lesson Jobs drew from it.',
    shareId: 'XrSa97dgHck',
    videoId: 'UF8uR6Z6KLc',
    source: jobsSource,
  },
  {
    slug: 'mcraven-make-your-bed',
    title: 'Admiral McRaven: Make Your Bed',
    blurb:
      'Ten lessons from Navy SEAL training, from making your bed to never ringing the bell, as ten readable branches.',
    shareId: 'h2CfqBUw6P4',
    videoId: 'pxBQLFLei70',
    source: mcravenSource,
  },
  {
    slug: 'hans-rosling-best-stats',
    title: "Hans Rosling: The best stats you've ever seen",
    blurb:
      'Global development in bubbles: what the fertility and life-expectancy axes actually show, and how the world moved across them.',
    shareId: '5-v5XwE6o50',
    videoId: 'hVimVzgtD6w',
    source: roslingSource,
  },
  {
    slug: 'randy-pausch-last-lecture',
    title: 'Randy Pausch: The Last Lecture',
    blurb:
      'Seventy-six minutes on achieving your childhood dreams, including the brick walls, condensed to one page.',
    shareId: 'khh1OA8U9xg',
    videoId: 'ji5_MqicxSo',
    source: pauschSource,
  },
]

/**
 * Root plus first-level branches only.
 *
 * These maps are 66 to 74 lines and render about 1500x4300, an aspect around
 * 0.35. Fitted whole into a card that is wider than it is tall, the labels come
 * out a few pixels high and the card reads as texture rather than as a diagram.
 * Trimming to depth 1 leaves 6 to 9 nodes at an aspect of 0.96 to 1.73, which
 * is card-shaped and legible. Same trick, and the same reason, as
 * MOBILE_DEMO_SOURCE in Landing.tsx.
 *
 * The card links to the full map; this only governs the thumbnail.
 */
export function previewSource(source: string): string {
  return source
    .split('\n')
    .filter((line) => line.startsWith('# ') || line.startsWith('- '))
    .join('\n')
}

/**
 * Canonical share page for an example, or null when no share base is
 * configured (a local dev build without VITE_SHARE_BASE, or a fork). Built from
 * SHARE_BASE rather than a literal domain so forks and zone config win, exactly
 * as shortenShareUrl does.
 *
 * `view=map` matches the links the Chrome extension hands out: the editor opens
 * with the source panel collapsed, map first.
 */
export function exampleShareUrl(example: Example): string | null {
  if (!SHARE_BASE) return null
  return `${SHARE_BASE}s/${example.shareId}?view=map`
}

/** The talk this map was generated from. */
export function exampleVideoUrl(example: Example): string {
  return `https://www.youtube.com/watch?v=${example.videoId}`
}
